name: unisat wallet extension

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Browser'
        options:
        - firefox
        - chrome

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Yarn
      uses: mskelton/setup-yarn@v1
      with:
        node-version: '14.x'
    - name: Build
      run: yarn build:${{ github.event.inputs.browser }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: unisat-${{ github.event.inputs.browser }}
        path: ./dist/
        
