name: unisat wallet extension

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Browser'
        options:
        - firefox
        - chrome

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: unisat-wallet/extension
        fetch-depth: 0
    - name: Set Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Install yarn
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build:${{ github.event.inputs.browser }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: unisat-${{ github.event.inputs.browser }}
        path: ./dist/        
