name: hysteria@wip-hy2

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'branch or sha'
        required: false
        default: wip-hy2

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        id: hy_sha
        uses: actions/checkout@v3
        with:
          repository: apernet/hysteria
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
      - run: |
          echo hy_sha=${git rev-parse HEAD}

      - name: Get latest go version
        id: version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Setup Python # This is for the build script
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run build script
        env:
          HY_APP_PLATFORMS: 'linux/amd64,linux/arm64'
          # CGO_ENABLED: 0
        run: 'python ./hyperbole.py build -r'

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: hy2-wip-${{ steps.hy_sha.outputs.hy_sha }}
          path: build
